### ISSUE TITLE
The device disappears after removed and usb and connected again

### ISSUE THREAD

**Issue by prasanthmk82** [sanyatuning/zigpy-cc#15]
Hi.
I am using CC2531 with latest beta of HA in ZHA integration, and find that if by any chance we remove the CC2531 from USB we had to remove the integration and add again for it to get recognzied.

**Comment by Hedda** [comment]
That must be a feature request as none of the current radio libraries for [zigpy](https://github.com/zigpy/zigpy) (with the exception of [bellows](https://github.com/zigpy/bellows)) currently has the function handle serial-port disconnects and reconnects. 

Not checked myself but my reference is a comment by @Adminiuga in https://github.com/zigpy/bellows/issues/183

Also see a somewhat related feature request by myself in https://github.com/zigpy/zigpy/issues/297
